MARKET: SNP
CURRENCY: USD
LOGLEVEL: ERROR
MAX_FILE_AGE: 1
MAX_DTE: 50
PORT: 1300
PAPER: 1301
CID: 10
MINCUSHION: 0.2
COVER_ME: true
COVER_MIN_DTE: 4
COVER_STD_MULT: 0.5
COVXPMULT: 1.5
SOW_NAKEDS: true
VIRGIN_DTE: 5
VIRGIN_CALL_STD_MULT: 2.5
VIRGIN_PUT_STD_MULT: 1.05
NAKEDXPMULT: 2.5
MINNAKEDOPTPRICE: 0.27
VIRGIN_QTY_MULT: 0.055
PROTECT_ME: false
PROTECT_DTE: 35
PROTECTION_STRIP: 5
REAP_ME: true
REAPRATIO: 0.3
MINREAPDTE: 1
